"""initial sauti schema

Revision ID: 831bbb629ae4
Revises: 
Create Date: 2026-08-07 04:25:03.924534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '831bbb629ae4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # All Sauti tables live in a dedicated schema; the same database hosts
    # other projects' tables in `public` — never touch anything outside `sauti`.
    op.execute("CREATE SCHEMA IF NOT EXISTS sauti")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='sauti'
    )
    op.create_table('users',
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='sauti'
    )
    op.create_table('voices',
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('consent_ref', sa.Text(), nullable=False),
    sa.Column('model_version', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('speaker'),
    schema='sauti'
    )
    op.create_table('levels',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('cefr', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['sauti.courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'cefr'),
    schema='sauti'
    )
    op.create_table('placement_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theta', sa.Float(), nullable=False),
    sa.Column('served', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('n_correct', sa.Integer(), nullable=False),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sauti'
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('pace_hours_week', sa.Integer(), nullable=False),
    sa.Column('placed_level', sa.Text(), nullable=True),
    sa.Column('gamification', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['sauti.courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='sauti'
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='sauti'
    )
    op.create_index('ix_refresh_family', 'refresh_tokens', ['family_id'], unique=False, schema='sauti')
    op.create_table('scenarios',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('setting', sa.Text(), nullable=False),
    sa.Column('persona', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('goals', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('min_cefr', sa.Text(), nullable=False),
    sa.Column('voice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['voice_id'], ['sauti.voices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title'),
    schema='sauti'
    )
    op.create_table('cando',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('cefr', sa.Text(), nullable=False),
    sa.Column('skill', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['sauti.levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'text'),
    schema='sauti'
    )
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('goals_met', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['sauti.scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sauti'
    )
    op.create_table('units',
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('situation_tag', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['sauti.levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level_id', 'ord'),
    schema='sauti'
    )
    op.create_index(op.f('ix_sauti_units_situation_tag'), 'units', ['situation_tag'], unique=False, schema='sauti')
    op.create_table('lessons',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('grammar_md', sa.Text(), nullable=False),
    sa.Column('culture_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['sauti.units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_id', 'ord'),
    schema='sauti'
    )
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=True),
    sa.Column('coach', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('audio_ref', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['sauti.conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sauti'
    )
    op.create_table('items',
    sa.Column('lesson_id', sa.UUID(), nullable=False),
    sa.Column('sentence', sa.Text(), nullable=False),
    sa.Column('gloss', sa.Text(), nullable=False),
    sa.Column('phoneme_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('audio_ref', sa.Text(), nullable=True),
    sa.Column('voice_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['sauti.lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_id'], ['sauti.voices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'sentence'),
    schema='sauti'
    )
    op.create_index('ix_items_tags', 'items', ['tags'], unique=False, schema='sauti', postgresql_using='gin')
    op.create_table('attempts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('audio_ref', sa.Text(), nullable=True),
    sa.Column('pron', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['sauti.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='sauti'
    )
    op.create_index('ix_attempts_user_ts', 'attempts', ['user_id', 'ts'], unique=False, schema='sauti')
    op.create_table('srs_state',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['sauti.items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id'),
    schema='sauti'
    )
    op.create_index('ix_srs_user_due', 'srs_state', ['user_id', 'due_at'], unique=False, schema='sauti')
    op.create_table('cando_status',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cando_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('confirmed_via_attempt', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cando_id'], ['sauti.cando.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_via_attempt'], ['sauti.attempts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['sauti.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cando_id'),
    schema='sauti'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cando_status', schema='sauti')
    op.drop_index('ix_srs_user_due', table_name='srs_state', schema='sauti')
    op.drop_table('srs_state', schema='sauti')
    op.drop_index('ix_attempts_user_ts', table_name='attempts', schema='sauti')
    op.drop_table('attempts', schema='sauti')
    op.drop_index('ix_items_tags', table_name='items', schema='sauti', postgresql_using='gin')
    op.drop_table('items', schema='sauti')
    op.drop_table('messages', schema='sauti')
    op.drop_table('lessons', schema='sauti')
    op.drop_index(op.f('ix_sauti_units_situation_tag'), table_name='units', schema='sauti')
    op.drop_table('units', schema='sauti')
    op.drop_table('conversations', schema='sauti')
    op.drop_table('cando', schema='sauti')
    op.drop_table('scenarios', schema='sauti')
    op.drop_index('ix_refresh_family', table_name='refresh_tokens', schema='sauti')
    op.drop_table('refresh_tokens', schema='sauti')
    op.drop_table('profiles', schema='sauti')
    op.drop_table('placement_sessions', schema='sauti')
    op.drop_table('levels', schema='sauti')
    op.drop_table('voices', schema='sauti')
    op.drop_table('users', schema='sauti')
    op.drop_table('courses', schema='sauti')
    # ### end Alembic commands ###
